### ISSUE TITLE
Error:java.lang.NoClassDefFoundError: Could not initialize class me.oriley.crate.mediainfo.MediaInfoLibrary

### ISSUE THREAD

**Issue by athkalia** [oriley-me/crate#6]
Hey there, really cool library!

Now trying to add it to my project.
I am having this issue when trying to refresh my gradle project:

`
Error:java.lang.NoClassDefFoundError: Could not initialize class me.oriley.crate.mediainfo.MediaInfoLibrary
`

Any idea on how to start investigating this?

Happening with Android Studio 2.2

**Comment by kaneoriley** [comment]
Hi, can you give me a sample project demonstrating the issue? Just confirmed the library is still working correctly with Android Studio 2.3, so I find it unlikely that 2.2 would have broken compatibility temporarily.

**Comment by kaneoriley** [comment]
Also, what operating system are you running on?

**Comment by athkalia** [comment]
Hey Pal,

windows 10. Sorry, extremely busy. I'll try to share a sample project with you on the weekend starting the 28th

**Comment by athkalia** [comment]
Hey again,

Had some time today so I forked a known project, added crate and I am still getting the same exception when syncing. Can you please have a look? This is the exact commit:

https://github.com/athkalia/qualitymatters/commit/61e29133eb803b5d3e94913fb708bfdfe3839bb7

Again, this is on Android Studio 2.2.3 , windows 10 64bit

exact message when syncing:

```
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies]
Error:java.lang.NoClassDefFoundError: Could not initialize class me.oriley.crate.mediainfo.MediaInfoLibrary
Information:BUILD SUCCESSFUL
Information:Total time: 1.931 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
```

**Comment by kaneoriley** [comment]
Hi,

I checked out that project and it works fine for me. So my only guess is that it is a Windows specific problem, and unfortunately I don't have access to a Windows machine to debug it myself at the moment.

**Comment by athkalia** [comment]
Thanks for your effort pal.
I'll try to figure it out. Does any place in the code come to your mind with regards to something that can be affected by the OS? Like file paths etc

**Comment by kaneoriley** [comment]
You could try running the task with `--debug` or `--stacktrace` to get more info as to where exactly it's breaking down, as the main error you're seeing is a symptom, not the cause.
